### ISSUE TITLE
Reply with Class Section

### ISSUE THREAD

**Issue by ProfRojas** [wilsonzhang6/CMPE-131-Grp10#1]

**Comment by wilsonzhang6** [comment]
Section 1

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by visvasuthar** [comment]
hello

**Comment by ngcuukhanh** [comment]
hello

**Comment by HughN7** [comment]
Greetings

**Comment by ProfRojas** [comment]
Thanks!
